[syscalls]
OPEN = 0x10
READ_CODE = 0x04
READ_MEM = 0x08
WRITE = 0x20
SLEEP = 0x01
EXIT = 0x02

[flags]
S = 0x00
G = 0x10
E = 0x01
N = 0x04
L = 0x02
Z = 0x08

[registers]
A = { enc = 0x04, addr = 0x400}
B = { enc = 0x08, addr = 0x401}
C = { enc = 0x10, addr = 0x402}
D = { enc = 0x20, addr = 0x403}
S = { enc = 0x02, addr = 0x404}
P = { enc = 0x40, addr = 0x405}
F = { enc = 0x01, addr = 0x406}

[instructions]
IMM = 0x10
ADD = 0x02
STK = 0x40
STM = 0x04
LDM = 0x80
CMP = 0x01
JMP = 0x20
SYS = 0x08

[encoding]
LEN = 0x03
ARG1 = 0x00
OP = 0x01
ARG2 = 0x02
MAX_VAL = 0xFF
